#!/bin/bash

# Improved Word Count. Basically just included recursive feature

cmd="wc"
args=""
IFS=' '

# Grab parameters to wc and add to iwc
for arg in "$@"; do
    if [ "$(echo $arg | grep -c -h '-')" != "0" ]; then
        cmd="$cmd $arg"
    else
        args="$args $arg"
    fi
done

line_sum=0
word_sum=0
char_sum=0

function rec() {
    for file in $@; do
        if [ -d $file ]; then
            rec "$file/*"
            continue
        fi
        wc=$($cmd $file)
        num=$(echo $wc | tr -d aA-zZ./)
        read -ra num_array <<< "$num"
        line_sum=$((line_sum + num_array[0]))
        word_sum=$((word_sum + num_array[1]))
        char_sum=$((char_sum + num_array[2]))
        name=$(echo $wc | tr -d 0-9)
        printf "\t%s\t%s\t%s\t%s\n" "${num_array[0]}" "${num_array[1]}" "${num_array[2]}" "$name"
    done
}

rec $args
printf "total\t%s\t%s\t%s\n" "$line_sum" "$word_sum" "$char_sum" 
